In [1]:
import pycountry
import pandas as pd
import numpy as np

### Get the credit dataset into Python

In [51]:
credit = pd.read_csv('data/originals/credit-ratings-3-2013.csv')
ratings_only = [x for x in credit.columns if 'Rating' in x or 'rating' in x or 'code' in x]
credit_clean = credit[ratings_only]
credit_clean.columns = ['Country Code','S&P Rating','Moody\'s Rating','Fitch Rating']
credit_clean.head(2)

  Country Code S&P Rating Moody's Rating Fitch Rating
0           IL         A+             A1            A
1           PL         A-             A2           A-

### Getting the debt dataset into Python

In [52]:
debt = pd.read_csv(open('data/originals/debt-gdp-percentage.csv','rU'),skiprows=4)
code_2012_2013 = [x for x in debt.columns if 'Country Code' in x or '2012' in x or '2013' in x]
debt_clean = debt[code_2012_2013]
debt_clean.is_copy = False
def code2to3(country):
    try:
        return pycountry.countries.get(alpha3=country).alpha2
    except:
        return "**"
debt_clean['Country Code'] = debt_clean['Country Code'].str.strip().apply(lambda x: code2to3(x))
debt_clean.columns = ['Country Code','2012-debt','2013-debt']
debt_clean.head(2)

  Country Code  2012-debt  2013-debt
0           AW        NaN        NaN
1           AD        NaN        NaN

### Getting the inflation dataset into Python

In [53]:
inflation = pd.read_csv(open('data/originals/inflation-gdp-percentage.csv','rU'),skiprows=4)
inflation_clean = inflation[code_2012_2013]
inflation_clean.is_copy = False
inflation_clean['Country Code'] = inflation_clean['Country Code'].str.strip().apply(lambda x: code2to3(x))
inflation_clean.columns = ['Country Code','2012-inflation','2013-inflation']
inflation_clean.head(2)

  Country Code  2012-inflation  2013-inflation
0           AW             NaN             NaN
1           AD        1.099967       -0.000194

### Combining the datasets through a join (just like in SQL)

In [64]:
finaldata = pd.merge(credit_clean, pd.merge(debt_clean, inflation_clean, how='left',on='Country Code'), how='left',on='Country Code')

In [65]:
finaldata.head(500)

,Country Code,S&P Rating,Moody's Rating,Fitch Rating,2012-debt,2013-debt,2012-inflation,2013-inflation
0,IL,A+,A1,A,NaN,NaN,3.886618,2.151554
1,PL,A-,A2,A-,55.155028,55.591572,2.386508,0.409000
2,MY,A-,A3,A-,51.646485,NaN,0.999828,0.176055
3,SI,A-,Baa2,A-,NaN,NaN,0.264515,0.842087
4,IT,BBB+,Baa2,A-,126.925184,134.653502,1.381143,1.288232
5,CZ,AA-,A1,A+,40.823490,NaN,1.387602,1.413977
6,EE,AA-,A1,A+,0.625415,0.629979,2.707062,3.972601
7,SK,A,A2,A+,53.309856,63.200014,1.263171,0.518660
8,MT,BBB+,A3,A+,87.130576,88.298227,2.182970,2.093391
9,CL,AA-,Aa3,A+,NaN,NaN,0.850031,1.895056
10,CN,AA-,Aa3,A+,NaN,NaN,2.392151,2.234965
11,JP,AA-,Aa3,A+,195.563179,201.129282,-0.931183,-0.548427
12,SY,AA-,Aa3,A+,NaN,NaN,NaN,NaN
13,KW,AA,Aa2,AA,NaN,NaN,7.486703,0.223536
14,BM,AA-,Aa2,AA,NaN,NaN,4.829612,3.245897
15,AE,NaN,Aa2,AA,NaN,1.907645,0.235536,-0.609568
16,BE,AA,Aa3,AA,103.813921,101.545212,2.038447,1.346088
17,NZ,AA,Aaa,AA,67.939285,60.190573,0.028286,4.046173
18,SA,AA-,Aa3,AA-,NaN,NaN,4.025153,-1.223004
19,HK,AAA,Aa1,AA+,NaN,NaN,3.544812,1.858365
20,FR,AA+,Aa1,AAA,88.923964,88.524567,1.157649,0.758611
21,GB,AAA,Aa1,AAA,101.950922,98.263984,1.625707,1.985034
22,AT,AA+,Aaa,AAA,85.383306,83.411002,1.957837,1.510309
23,AU,AAA,Aaa,AAA,40.409631,38.339184,2.055914,-0.199371
24,CA,AAA,Aaa,AAA,52.108585,48.843860,1.506558,1.383477
25,DK,AAA,Aaa,AAA,49.371136,46.568663,2.491938,1.544405
26,FI,AAA,Aaa,AAA,52.465302,53.688167,2.953564,2.627180
27,DE,AAA,Aaa,AAA,55.227852,52.333719,1.502825,2.090241
28,LU,AAA,Aaa,AAA,20.146620,NaN,4.071949,2.359837
29,NL,AAA,Aaa,AAA,68.536372,68.272908,1.419672,1.384648
...,...,...,...,...,...,...,...,...
110,KH,B,B2,NaN,NaN,NaN,1.373747,2.247733
111,HN,B+,B2,NaN,NaN,NaN,3.579787,1.374031
112,VC,NaN,B2,NaN,NaN,NaN,1.089831,2.289600
113,BA,B,B3,NaN,47.782804,46.003594,0.878158,-0.287407
114,BY,B-,B3,NaN,25.224365,NaN,75.438581,21.091582
115,MDA,NaN,B3,NaN,NaN,NaN,NaN,NaN
116,NI,NaN,B3,NaN,NaN,NaN,7.094701,4.212743
117,BB,BB+,Ba1,NaN,120.541899,131.631527,-1.300304,-0.741943
118,JO,BB,Ba2,NaN,66.823528,NaN,4.500610,5.599315
119,BD,BB-,Ba3,NaN,NaN,NaN,8.164598,7.174963
120,ME,BB-,Ba3,NaN,NaN,NaN,0.177026,2.066968
121,TO,A,Baa1,NaN,NaN,NaN,2.498774,0.343305
122,BS,BBB,Baa1,NaN,NaN,NaN,2.105221,2.373230
123,MUS,NaN,Baa1,NaN,NaN,NaN,NaN,NaN
124,SX,NaN,Baa1,NaN,NaN,NaN,NaN,NaN
125,NaN,NaN,Baa3,NaN,NaN,NaN,NaN,NaN
126,BZ,SD,Ca,NaN,74.471145,NaN,1.942345,1.653119
127,PK,B-,Caa1,NaN,NaN,NaN,5.968574,6.964041
128,CU,NaN,Caa1,NaN,NaN,NaN,2.911615,2.724386
129,AD,A-,NaN,NaN,NaN,NaN,1.099967,-0.000194
130,LI,AAA,NaN,NaN,NaN,NaN,NaN,NaN
131,BJ,B,NaN,NaN,NaN,NaN,7.402100,1.626402
132,BF,B,NaN,NaN,NaN,NaN,5.823999,1.290898
133,CK,B+,NaN,NaN,NaN,NaN,NaN,NaN
134,MS,BBB-,NaN,NaN,NaN,NaN,NaN,NaN
135,GD,CCC+,NaN,NaN,NaN,NaN,3.927634,2.916041
136,GG,NaN,NaN,NaN,NaN,NaN,NaN,NaN
137,LY,NaN,NaN,NaN,NaN,NaN,18.967659,-6.753192
138,ML,NaN,NaN,NaN,NaN,NaN,5.044580,0.685275
139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN